### PR TITLE
✨ Adds Norwegian translation.

### PR DESCRIPTION
**Pull request by tplive**
I've punched up the Norwegian translation as I want my family and friends to print their own cards.. ;)

### CODE REVIEW

**Review by Starefossen — APPROVED** [review]

**Comment by Starefossen** [comment]
Awesome 😍

**Review by bndw — COMMENTED** [review]
Hi @tplive thanks for the translation! Would you mind running `make fmt.write` to format the changes (looks like the pre-commit hook didn't run 🤔 ) and I'd be happy to merge

**Comment by tplive** [comment]
Sorry, I kinda jumped the gun on the first PR. Back at work from a long vacation an eager to make a contribution. :) Fixed the formatting, but then I see that Korean has also been added to master. Resolved that merge in a separate branch, think it should be ok.

**Review by bndw — COMMENTED** [review]
Just a small ordering change and we're good! Thanks again ❤️

**Comment by tplive** [comment]
...and if all those merges add up to that simple change, we're all set! 😅

**Review by bndw — APPROVED** [review]
🎉

**Pull request merged**
