### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by dk90103**

### CODE REVIEW

**Comment by ous50** [comment]
please change your Line Seperator from CRLF to LF

**Comment by dk90103** [comment]
> please change your Line Seperator from CRLF to LF

Done

**Comment by bndw** [comment]
Hi @dk90103 thanks for the contribution. It looks like you've moved `./src/translations.js` to `./translations.js`, breaking the app. Do you want to try again?

**Comment by dk90103** [comment]
Done 😊

 

Fra: Ben Woodward ***@***.***> 
Sendt: Saturday, 4 June 2022 23.49
Til: bndw/wifi-card ***@***.***>
Cc: dk90103 ***@***.***>; Mention ***@***.***>
Emne: Re: [bndw/wifi-card] Add files via upload (PR #242)

 

Hi @dk90103 <https://github.com/dk90103>  thanks for the contribution. It looks like you've moved ./src/translations.js to ./translations.js, breaking the app. Do you want to try again?

**Comment by bndw** [comment]
Implemented in https://github.com/bndw/wifi-card/pull/248

**Pull request closed without merging**
