### PR TITLE
Add support for EAP-PWD

### PR DESCRIPTION
**Pull request by jantatje**
I added support for WPA2-EAP authentication with the PWD method. I also added a German translation of the new strings. Other languages will have to be updated by someone who knows them.

When the EAP method and identity fields are hidden there is a small additional gap that I don't know how to get rid of. If that is an issue, I would appreciate some help with fixing that.

### CODE REVIEW

**Comment by bndw** [comment]
Hi @jantatje and thanks for the contribution. I'm not familiar with WPA-EAP with PWD, any idea how widely used this configuration is? Now this this project has grown to support so many languages it's somewhat of a balancing act when changing/adding text.

**Comment by jantatje** [comment]
PEAP and TTLS are probably the most common, but also need a certificate that I don't think you can add to the QR code. PWD is easier to use and doesn't need certificates, but still allows you to have separate identities and passwords for each user. I have no idea how widely it is used.

As for language support, I do not think it is a big deal considering that the new strings are only used if you select EAP. So 99% of home users should never see these untranslated bits of text and the 1% of users that do use EAP-PWD will still have a better experience even with three or four possibly untranslated strings. Otherwise they would have to craft a string like "WIFI:T:WPA2-EAP;S:wifi;P:password;E:PWD;I:user;;" by hand, manually create a QR code and then paste it in a word doc and add the login credentials as text to achieve the same result.

**Comment by bndw** [comment]
I appreciate the detailed response and agree, the language support shouldn't be a big deal considering it's additive. I'll give this a spin locally and review the code soon.

**Comment by bndw** [comment]
@jantatje Nice work and thanks for the contribution.

**Pull request merged**
