### PR TITLE
Add Indonesia translation

### PR DESCRIPTION
**Pull request by riipandi**
Hello,

I've added an Indonesian translation.

Thank you.

### CODE REVIEW

**Comment by bndw** [comment]
Hi @riipandi We have an existing pull request for an Indonesian translation in https://github.com/bndw/wifi-card/pull/109. Would you mind reviewing that pull request since it came in first?

**Comment by riipandi** [comment]
Hi @bndw Yeah, I've already reviewed for PR #109, seems like there is a typo and conflict right there.
I don't mind if you will combine the previous homework and ignore my PR.
 
 Thank you.

**Comment by bndw** [comment]
@riipandi Let's give the other PR a chance to resolve the typo and conflicts. If it's stale for more than a few days I'll close it out in favor of yours.

**Comment by riipandi** [comment]
> @riipandi Let's give the other PR a chance to resolve the typo and conflicts. If it's stale for more than a few days I'll close it out in favor of yours.

Sure @bndw

**Comment by nyancodeid** [comment]
> @riipandi Let's give the other PR a chance to resolve the typo and conflicts. If it's stale for more than a few days I'll close it out in favor of yours.

Cool, I'll fix it tomorrow. thanks guys.

**Comment by riipandi** [comment]
> > @riipandi Let's give the other PR a chance to resolve the typo and conflicts. If it's stale for more than a few days I'll close it out in favor of yours.
> 
> Cool, I'll fix it tomorrow. thanks guys.


Yeah, anytime @nyancodeid :-)

**Comment by bndw** [comment]
Landed in https://github.com/bndw/wifi-card/pull/141

**Pull request closed without merging**
