### PR TITLE
[Issue #49] feat: add i18n

### PR DESCRIPTION
**Pull request by Baoyuantop**

### CODE REVIEW

**Comment by Baoyuantop** [comment]
Resolves issue #49

**Comment by bndw** [comment]
Hi @Baoyuantop, thank you this is so cool! Would you mind running `make fmt.write` to format the code with Prettier? I'd love to merge this in with that change.

**Comment by Baoyuantop** [comment]
Sure

**Comment by bndw** [comment]
@Baoyuantop Sorry, but would you mind rebasing master? This pull request is next in line so this will be merged following that.

**Comment by Baoyuantop** [comment]
@bndw Done

**Pull request merged**
