### PR TITLE
Catalan translation

### PR DESCRIPTION
**Pull request by aniol**
Catalan translation

### CODE REVIEW

**Comment by Teraskull** [comment]
You forgot to add an option entry for the language in [App.js](https://github.com/bndw/wifi-card/blob/0eea7b56a67f40c1cb8520ecb41fae19966be8ad/src/App.js#L31).

**Comment by aniol** [comment]
> 
> 
> You forgot to add an option entry for the language in [App.js](https://github.com/bndw/wifi-card/blob/0eea7b56a67f40c1cb8520ecb41fae19966be8ad/src/App.js#L31).

Thanks @Teraskull, just added: #85

**Review by bndw — CHANGES_REQUESTED** [review]
Hi @aniol and thanks for the contribution. Would you please include the changes from https://github.com/bndw/wifi-card/pull/85 in this branch and make sure to run `make fmt.write` to format your changes with Prettier?

**Comment by Andanan** [comment]
There is also no entry in the supported languages table in `README.md`

**Comment by bndw** [comment]
Implemented in https://github.com/bndw/wifi-card/pull/138

**Pull request closed without merging**
