### PR TITLE
Fix QR code sharpness/blur

### PR DESCRIPTION
**Pull request by ismaelpereira**
To fix the blur i just add the `renderAs = "svg"` proprierty in QRCode component

### CODE REVIEW

**Comment by noahhefner** [comment]
Rendering as an SVG introduces some scaling quirks:
svg1
svg2
Not neccessarily a good/bad thing, just wanted to drop these screenshots here for review.

**Comment by ismaelpereira** [comment]
I think if this don't make the QR unreadable, it's okay. There's another solution for this blur problem?

**Comment by noahhefner** [comment]
I think SVG is the way to go, my concern is that IDK how well it will scale on various resolutions (like HiDPI screens or low resolution screens.)

**Comment by ismaelpereira** [comment]
The most likely behavior is work normally, on the way PDF works, the archive will scale okay, because SVG and PDF are vectorized formats

**Comment by bndw** [comment]
Hi @ismaelpereira thanks for the contribution! I played around with the styles of the svg and was able to keep it pretty consistent with how it looks today by explicitly applying a min and max width. Do you want to try the below change and if it looks good to you, include it in this pull request? 

Also, please be sure to run `make fmt.write` to format your changes with Prettier.

```diff
diff --git a/src/components/style.css b/src/components/style.css
index e6973f0..c9dbb54 100644
--- a/src/components/style.css
+++ b/src/components/style.css
@@ -15,6 +15,8 @@
 
 .qrcode {
   margin-bottom: 1em;
+  max-width: 175px;
+  min-width: 175px;
 }
 
 .hidden {

```

**Review by bndw — CHANGES_REQUESTED** [review]
Hi @ismaelpereira thanks for the contribution! I played around with the styles of the svg and was able to keep it pretty consistent with how it looks today by explicitly applying a min and max width. Do you want to try the below change and if it looks good to you, include it in this pull request? 

Also, please be sure to run `make fmt.write` to format your changes with Prettier.

```diff
diff --git a/src/components/style.css b/src/components/style.css
index e6973f0..c9dbb54 100644
--- a/src/components/style.css
+++ b/src/components/style.css
@@ -15,6 +15,8 @@
 
 .qrcode {
   margin-bottom: 1em;
+  max-width: 175px;
+  min-width: 175px;
 }
 
 .hidden {

```

**Comment by bndw** [comment]
Fixes #82

**Comment by bndw** [comment]
@ismaelpereira Looks good to me! Please run `make fmt.write` to format the changes, then squash these into a single commit and I'll get this merged.

**Comment by bndw** [comment]
Resolved rebase conflicts and merged in https://github.com/bndw/wifi-card/pull/139

**Pull request closed without merging**
