### PR TITLE
Hungarian translation

### PR DESCRIPTION
**Pull request by munkacsimark**
- Added hungarian translations
- Fixed translation of 'None' field at encryption

### CODE REVIEW

**Comment by munkacsimark** [comment]
Should sync with #168

**Comment by bndw** [comment]
Hi @munkacsimark thanks for the translation! #168 has landed, would you mind rebasing?

**Comment by munkacsimark** [comment]
@bndw Updated the PR and fixed another small bug at SelectField. :)
Thanks!

**Review by bndw — APPROVED** [review]
Looks great, and thanks for the bug fix 😅

**Comment by bndw** [comment]
Sorry I missed it -- want to add a row to the [Supported Languages](https://github.com/bndw/wifi-card#supported-languages) in the README?

**Comment by munkacsimark** [comment]
@bndw sorry, my bad, I made a new PR (#175) 🙃

**Pull request merged**
