### PR TITLE
i18n: small update for Occitan

### PR DESCRIPTION
**Pull request by Mejans**
Changes for the EAP method entries

### CODE REVIEW

**Comment by bndw** [comment]
Hi @Mejans, thanks for the contribution! Would you mind running `make fmt.write` to fix the linter errors?

**Comment by bndw** [comment]
Merged in https://github.com/bndw/wifi-card/pull/255

**Comment by Mejans** [comment]
Oh sorry, I didn't how to do that :S Thanks for making it!

**Comment by bndw** [comment]
No problem, thanks again for the contribution!

**Pull request closed without merging**
