### PR TITLE
feat: add possibility to hide password field before printing

### PR DESCRIPTION
**Pull request by orenaksakal**
#32

### CODE REVIEW

**Comment by bndw** [comment]
@orenaksakal 👋 thanks for the contribution!

I tested it out locally and noticed the password and checkbox weren't being hidden from the print dialogue, so I took what you have and added additional CSS and another small tweak in https://github.com/bndw/wifi-card/commit/5927e1afaf15366f0b69edc0b7dda6374331956a.

Let me know if you'd like to pull that commit into your branch, or I can open a PR for https://github.com/bndw/wifi-card/tree/orenaksakal-master (your commit/contribution is still in there).

image

**Comment by orenaksakal** [comment]
> @orenaksakal 👋 thanks for the contribution!
> 
> I tested it out locally and noticed the password and checkbox weren't being hidden from the print dialogue, so I took what you have and added additional CSS and another small tweak in [5927e1a](https://github.com/bndw/wifi-card/commit/5927e1afaf15366f0b69edc0b7dda6374331956a).
> 
> Let me know if you'd like to pull that commit into your branch, or I can open a PR for https://github.com/bndw/wifi-card/tree/orenaksakal-master (your commit/contribution is still in there).
> 
> image

Hi @bndw, somehow style changes were not staged I added the style.css now it should be good to go

**Review by bndw — CHANGES_REQUESTED** [review]
Overall looks good, with one small change requested.

**Comment by bndw** [comment]
@orenaksakal You'll also need to run the files through [Prettier](https://prettier.io/) for the automated checks to pass. Here's the command to auto-format the code from the root of the repository:
```
npx prettier --write . '!**/*.min.{css,js}'
```

**Comment by bndw** [comment]
I took this and implemented the two review comments in #42

**Pull request closed without merging**
