### PR TITLE
add yue-CN translation and slightly modify zh-HK, and append an entry of translators

### PR DESCRIPTION
**Pull request by ous50**

### CODE REVIEW

**Comment by bndw** [comment]
Hi @ous50 and thanks for the contribution! 👋

**Comment by ous50** [comment]
no problem :)

**Comment by ous50** [comment]
Seems wificard.io is not updated. Just for reminding. :)

**Comment by bndw** [comment]
Might have taken a few to propagate but it's there now!

image

**Comment by ous50** [comment]
Oh that's good :)

**Pull request merged**
