### PR TITLE
Update i18n.js to add Italian translation

### PR DESCRIPTION
**Pull request by pasmimmo**
added Italian translation

### CODE REVIEW

**Comment by Baoyuantop** [comment]
Looks like you are missing some steps #117

**Comment by pasmimmo** [comment]
done

**Comment by Baoyuantop** [comment]
> done

README ？

**Comment by pasmimmo** [comment]
sorry i forgot to push all files, thank you for your patience, now all should be ok

**Comment by Baoyuantop** [comment]
It looks like you need to merge the latest master branch and resolve conflicting files

**Review by Baoyuantop — APPROVED** [review]

**Comment by bndw** [comment]
Thanks @pasmimmo , merged in https://github.com/bndw/wifi-card/pull/145

**Pull request closed without merging**
