### PR TITLE
Improve Portuguese translation to Portugal PT-pt

### PR DESCRIPTION
**Pull request by hjgraca**
Improve Portuguese translation to Portugal PT-pt

### CODE REVIEW

**Review by bndw — APPROVED** [review]
Hi @hjgraca and thanks for the contribution! Would you mind running `make fmt.write` to format the source code changes?

@pedrorenan Would you mind reviewing these updates?

**Comment by A-Tokyo** [comment]
@pedrorenan @hjgraca The current main branch has both pt-BR and pt-PT. I think @hjgraca should pull the latest upstream and merge his translation into pt-PT! ( :

**Comment by hjgraca** [comment]
> @pedrorenan @hjgraca The current main branch has both pt-BR and pt-PT. I think @hjgraca should pull the latest upstream and merge his translation into pt-PT! ( :

Hey, that is exactly what I've done, replaced the existing "pt" text and left "pt-br" as it was.

**Comment by hjgraca** [comment]
> > Hi @hjgraca and thanks for the contribution! Would you mind running `make fmt.write` to format the source code changes?
> > @pedrorenan Would you mind reviewing these updates?
> 
> I think @hjgraca should change my first translation to pt-br and create pt-pt.

Not sure what you mean, there were already two Portuguese translations, one "pt" and the other "pt-br", I have changed the text in "pt" language.

**Comment by pedrorenan** [comment]
@bndw It's ok! @hjgraca is from Lisbon. He knows pt better.

**Comment by bndw** [comment]
Thanks @hjgraca !

**Pull request merged**
