### PR TITLE
Unset password when encryption mode is 'None'

### LINKED ISSUE #46: Clear network.password when "None" encryption mode is selected
> When selecting "None" encryption, the network.password field remains unchanged. In my testing, the password will actually change the QR code that is generated for None encryption. So assuming that we want to have no password for None encryption, we will need to clear network.password when upon selection of None encryption. Something like this:
>
> ```
> setNetwork({ ...network, password: '' })
> ```

_Originally posted by @noahhefner in https://github.com/bndw/wifi-card/issues/44#issuecomment-880759353_

### PR DESCRIPTION
**Pull request by thealamu**
Fixes #46

### CODE REVIEW

**Comment by bndw** [comment]
@thealamu Please run `make fmt.write` to format the source files with Prettier so the CI checks pass.

**Comment by thealamu** [comment]
Sorry about that. Done @bndw

**Comment by bndw** [comment]
@thealamu No problem and thanks. Looks like you'll need to rebase master for me to merge now. Let me know if you need any assistance, sorry!

**Comment by thealamu** [comment]
Should be good to go @bndw

**Pull request merged**
