### PR TITLE
Document supported languages

### PR DESCRIPTION
**Pull request by bndw**
Documents supported languages in the README with credit to the authors. Please let me know if you'd prefer your Github username not listed.

cc: 
- @Baoyuantop
- @oscfdezdz 
- @pedrorenan
- @hatsu38
- @Teraskull 
- @wouterbrink

Also, thanks @Teraskull for the inspiration for this in https://github.com/Teraskull/PyDebloatX

### CODE REVIEW

**Comment by pedrorenan** [comment]
Its ok for me. Thank you

**Comment by olekstomek** [comment]
A very good option, although it seems that it will significantly extend the implementation of new functionalities. Maybe it is better to translate only what is visible on the print card? I'm just wondering and maybe I'm wrong.

**Comment by Andanan** [comment]
In my opinion all texts on the Web-UI should be translated as well. Not all people understand english or are comfortable with it. Otherwise only a limited set of users would be able to use the application and create printed cards.

On the other hand I have to agree with olekstomek that it will take some time to translate each new functionality to all available Languages. But that is probably the case for every application that targets an international userbase.

It would probably be good to keep track of which feature is supported by which translation. And each translation should have somebody that is 'responsible' for keeping it up-to-date. If such a process is in place it would probably be enough to provide the english default texts for a new feature at the time this feature is implemented. The translations would then be added over time.

**Comment by olekstomek** [comment]
One more idea: [https://support.google.com/chrome/answer/173424?hl=en&co=GENIE.Platform%3DAndroid&oco=1#zippy=%2Crequest-translation-or-turn-translation-off%2Cturn-translation-on-or-off-for-a-specific-language](Translate webpages in Chrome) :)
Dynamic translation into almost all languages.  I think it can be achieved in any browser with the help of Google, Bing etc.

**Comment by Andanan** [comment]
Please be aware that only because you use Chrome or another Chromium-based browser (sorry if my assumption is wrong) it doesn't mean that everyone does! Therefore that would only work for some users, but certainly not for all. And (luckily) not all browsers include a dynamic translation feature. (As far as i know Firefox and Safari don't... At least not out-of-the-box)
I admit, that such a feature would be handy at some times, but at what cost? Letting Google (or any other translation service) keep track of your browsing history? If you don't care: I'm totally fine with that. But PLEASE don't force it onto people that do care!

Sure, there are probably browser-independent solutions that could integrate a dynamic translation-feature, but it would be really uncool to include such privacy-invading external services. Currently it's a great feature, that the Wifi-Card web app does not connect to the outside in any way once it's loaded and does not include third-party services. Let's not screw that up by including Google (or Bing, ...) services.

**Comment by olekstomek** [comment]
Ok, then let me give you one more idea. I do not know how technically this is a feasible solution in this project: https://github.com/vslavik/poedit

**Comment by Andanan** [comment]
Looks interesting, but as far as i can tell poedit works on the po file format of gettext and would therefore require an additional conversion-layer. I found a [translation-backend plugin](https://github.com/palamccc/i18next.gettext) for i18next that adds support for the gettext format (at least as i understand it) but it's repo is inactive since 2014 so i don't know whether it still works.

Do you have arguments for using poedit that are strong enought to justify the change of the translation file format?

**Comment by olekstomek** [comment]
I am actually giving these various suggestions for consideration. I am not in favor of any particular solution. I raised the topic of translation to simplify this operation and to easily achieve the result that the languages in the entire application will be up-to-date. It is worth seeing what are the ways.

**Pull request merged**
