### PR TITLE
Make dropdown language display consistent

### LINKED ISSUE #80: Make the language names consistent
Right now the dropdown languages are written in three different ways:
1. Locale name
2. Full name in that language
3. Language code
image

My suggestion is to have the names show like in [Ventoy](https://github.com/ventoy/Ventoy):
image
The full name in English, and the translated name in brackets.

For i18n, the international locale codes should be used, as found [here](http://www.lingoes.net/en/translator/langcode.htm).
```js
'en-US': {
    translation: {
...
```

### PR DESCRIPTION
**Pull request by kishorbhat**
Fixes #80.

Thanks for the project!

### CODE REVIEW

**Review by bndw — CHANGES_REQUESTED** [review]
Hi @kishorbhat thanks for the contribution! Would you mind running `make fmt.write` to format the changes with Prettier, then I'd be happy to merge.

**Comment by bndw** [comment]
https://github.com/bndw/wifi-card/pull/86 also introduced `Brazilian Portuguese`

**Comment by kishorbhat** [comment]
Updated to include Brazilian Portuguese and Chinese - Hong Kong. Ran `make fmt.write` too. 👍🏼

**Comment by bndw** [comment]
@kishorbhat Just merged https://github.com/bndw/wifi-card/pull/79 for Persian support and the last PR before yours -- mind doing one more rebase and I'll get this in?

**Comment by kishorbhat** [comment]
Sorry for the wait. Added Persian and Turkish.

**Comment by bndw** [comment]
Thanks @kishorbhat, your work has been merged in https://github.com/bndw/wifi-card/pull/137

**Pull request closed without merging**
