### PR TITLE
Added Greek translation

### PR DESCRIPTION
**Pull request by nautilus7**

### CODE REVIEW

**Comment by bndw** [comment]
👋 Hey @nautilus7 thanks for the translation! Mind running `make fmt.write`, it looks like it's failing the linter.

**Comment by nautilus7** [comment]
Hi, where do I run this command and what it does?

**Comment by bndw** [comment]
You run it from the root of the repository. It runs [prettier](https://prettier.io/) to format the code. The build is failing because one of the strings uses `"double quotes"` instead of `'single quotes'`. Running this command will fix that.

The command is specified in the [Makefile](https://github.com/bndw/wifi-card/blob/master/Makefile#L22-L23)

**Comment by nautilus7** [comment]
Got, it. Will fix it later tonight.

**Comment by bndw** [comment]
Fixed lint in https://github.com/bndw/wifi-card/pull/253

**Pull request closed without merging**
