### PR TITLE
Feature add polish language i18

### PR DESCRIPTION
**Pull request by olekstomek**
https://github.com/bndw/wifi-card/pull/90

### CODE REVIEW

**Comment by bndw** [comment]
@olekstomek Mind rebasing once more? I just merged Turkish.

Aside: I'm planning to stop using Squash and merge soon. I strongly prefer features to land in master in a single commit, which is why I've been squashing, but I'll instead start asking contributors to squash their commits after approval and use a standard merge into master. This should cut down on the required rebasing after every merge.

**Comment by bndw** [comment]
Additionally, want to add a row to the Supported Languages table in the README?

**Comment by olekstomek** [comment]
Ok I updated this PR and I added me to table in README.

**Review by Baoyuantop — APPROVED** [review]

**Comment by bndw** [comment]
Thanks @olekstomek , resolved conflicts and merged in https://github.com/bndw/wifi-card/pull/142

**Pull request closed without merging**
