### PR TITLE
Made few translation corrections

### LINKED ISSUE #158: A few translation corrections
A few translation corrections:
Russian: "Нет"
Ukrainian: "Немає"
Polish: "Brak"

_Originally posted by @Teraskull in https://github.com/bndw/wifi-card/issues/157#issuecomment-890391952_

### PR DESCRIPTION
**Pull request by RhnSharma**
Fixes #158
Hi @bndw @Teraskull, how does this look?
Let me know if this needs any changes.
Thanks

### CODE REVIEW

**Comment by Teraskull** [comment]
Looks good, now we just need to confirm the translations for the rest.

**Comment by bndw** [comment]
https://github.com/bndw/wifi-card/commit/444b2c5b267fb5d454091ad373df47fd9b84beae#r54247151

**Comment by RhnSharma** [comment]
@bndw I have made the change you suggested. Please take a look at it and let me know if this needs any changes.
Thanks

**Comment by Mejans** [comment]
lil corrections:
in French: it would be "Aucun" and not "Rien"
in Occitan it would be "còdi" not "còde", my typo :S

**Comment by RhnSharma** [comment]
> lil corrections:
> in French: it would be "Aucun" and not "Rien"
> in Occitan it would be "còdi" not "còde", my typo :S

@bndw Should I commit after making these changes or should I wait for more corrections?

**Comment by bndw** [comment]
@RhnSharma If you want to make those corrections I'd be happy to merge. Any further translation correction can be filed in a new issue.

**Comment by RhnSharma** [comment]
> @RhnSharma If you want to make those remaining corrections, I'd be happy to merge after. Any further translation correction can be filed in a new issue.

@bndw I have made the changes. Please take a look at it and let me know if this needs any changes.
Thanks

**Review by bndw — APPROVED** [review]
Thanks @RhnSharma !

**Pull request merged**
