### PR TITLE
Added en-GB translations

### PR DESCRIPTION
**Pull request by benjisoft**

### CODE REVIEW

**Comment by bndw** [comment]
Hi @benjisoft , this looks to be the exact same as the `en-US` default translation. Perhaps we should just rename `en-US` to `en` until a locale-specific English is necessary. I would also expect the language to default to English, so even if your browser/PC is set for `en-GB` you're still getting this same translation.

Is there a compelling reason to duplicate the English translation here?

**Comment by benjisoft** [comment]
Hey, 

There are often a few subtle differences but I don't believe there are here. 

The main reason was just the annoyance that English is always seen as American by Americans. Although #149 does seem more appropriate in this case.

**Comment by bndw** [comment]
👍 Let's go with the generic English translation for now, then.

**Comment by bndw** [comment]
@benjisoft I've had to revert the generic `en` language to the locale-specific `en-US` in https://github.com/bndw/wifi-card/pull/153 due to a language-detection regression. So now that we're back to American English, I'd be happy to accept a PR for British English.

**Pull request closed without merging**
